# Generated by Django 4.1.1 on 2022-10-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agriculteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=100)),
                ('Tel', models.IntegerField()),
                ('Région', models.CharField(max_length=100)),
                ('bref_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=250)),
                ('categorie', models.CharField(choices=[('cereal', 'Céréal'), ('maraichere', 'Maraichere'), ('coton', 'Coton')], default='Cereal', max_length=100)),
                ('maraichere', models.CharField(choices=[('fruit', 'Fruit'), ('legume', 'Légume')], default='Fruit', max_length=100)),
                ('Prix', models.FloatField()),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
