# Generated by Django 4.1.2 on 2022-10-24 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='image',
        ),
    ]
