# Generated by Django 4.1.2 on 2022-10-25 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_produit_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='Nom',
            new_name='Nom_produit',
        ),
    ]
