# Generated by Django 4.1.2 on 2022-12-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
